### PR TITLE
Strengthen immutability and price data integrity

### PR DESCRIPTION
**Pull request by mbouchenoire**
- Immutable lists are built inside the `SteamApp` constructor to avoid external mutation between construction and usage ;
- As `BigDecimal` class is mutable, its values are safe-copied when necessary ;
- Price values cannot be null, allowing surface checks to be removed ;
- None of these changes alter the library API.

### CODE REVIEW

**Comment by go-ive** [comment]
I like most of your changes and would like to merge this PR, but there are a few things I would like you to change/have a look before that:

* SteamApp line 51: Use swirly braces on ifs, even with just one statement. Also instead of a NPE, please throw a SteamApiException (this should be the only one used in the context of the project, unless there is need for a more specific one).
* SteamApp line 306-314: same thing, swirly braces and SteamApiException.
* SteamApp line 316,317,326,330: BigDecimal is immutable as far as I know. Any particular reason the pass a copy here?
* SteamAppBuilder line 18: Are you sure the date is always formatted in the US locale?
* SteamAppBuilder line 15: The USD field is redundant.

**Comment by mbouchenoire** [comment]
I will add curly braces one single-line ifs

> SteamApp line 316,317,326,330: BigDecimal is immutable as far as I know. Any particular reason the pass a copy here?

BigDecimal is indeed immutable, my bad. I will fix this.

> SteamAppBuilder line 18: Are you sure the date is always formatted in the US locale?

I'm not sure about it, but it's the current behavior. I just made a "constant" as a good practice.

> SteamAppBuilder line 15: The USD field is redundant.

I will remove it.

> instead of a NPE, please throw a SteamApiException (this should be the only one used in the context of the project, unless there is need for a more specific one).

Can we discuss this one ? I feel like obligating the client to handle a checked exception for this behavior might be too heavy. In fact, it seems like even a [NullPointerException](https://docs.oracle.com/javase/7/docs/api/java/lang/NullPointerException.html) is not appropriate for this, as its valid usages do not include parameters assertion. On the other hand, [IllegalArgumentException](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/IllegalArgumentException.html) might fit this case perfectly, as its description shows : 
> Thrown to indicate that a method has been passed an illegal or inappropriate argument.

I'm waiting for you final word on this, as it's a design choice.

**Comment by go-ive** [comment]
Hi, sorry I'm taking so long, but work is quite demanding this week. I'll have a closer look on that over the weekend.

**Comment by go-ive** [comment]
So, about the NPE with the pricing data: I think we should not throw anything here and just have a nullcheck as it was before.

My reasoning for this is that it is not up to the user to handle an inconsistency of the actual steam API. When there is incomplete or missing price data, a fallback handling should be done so that it is transparent to the API user.

Whatever exception you throw in these cases, you have to handle them yourself and still return some valid values to the user for pricing (BigDecimal.ZERO or isFree() == true). What do you think?

**Comment by mbouchenoire** [comment]
The `IllegalArgumentException` is not a checked exception, meaning the user does not have to handle it if we instanciate `SteamApp` within the library or if the client does it himself (let's not forget that he can do that, as it's a public class).

I strongly feel that doing null checks after the "corrupted" instance has been constructed (with a null price) is putting the problem under the rug and forces us to manage the corrupted object state. As Martin Fowler explained somewhere (I cant' find the article now), an object state should be valid as soon as possible, meaning immediatly after its construction.

**Comment by go-ive** [comment]
That makes sense to me. In that case, throw the IllegalArgumentException. Unfortunately the user will not have a way to deal with this except raising an issue here or fixing it in the Steam Api code themselves.

When you have the change ready, I'll merge it. Sorry it took so long.

**Pull request merged**
